# Notification Workflow
# Reusable workflow for Slack/Discord notifications
# qr-pipeline - QuantumRishi

name: Notify

on:
  workflow_call:
    inputs:
      status:
        description: 'Build status (success, failure, cancelled)'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: false
        type: string
        default: ''
      message:
        description: 'Custom message'
        required: false
        type: string
        default: ''
    secrets:
      SLACK_WEBHOOK_URL:
        description: 'Slack webhook URL'
        required: false
      DISCORD_WEBHOOK_URL:
        description: 'Discord webhook URL'
        required: false

jobs:
  notify:
    name: Send Notification
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Determine status emoji
        id: status
        run: |
          case "${{ inputs.status }}" in
            success)
              echo "emoji=✅" >> $GITHUB_OUTPUT
              echo "color=#36a64f" >> $GITHUB_OUTPUT
              ;;
            failure)
              echo "emoji=❌" >> $GITHUB_OUTPUT
              echo "color=#dc3545" >> $GITHUB_OUTPUT
              ;;
            cancelled)
              echo "emoji=⚠️" >> $GITHUB_OUTPUT
              echo "color=#ffc107" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "emoji=ℹ️" >> $GITHUB_OUTPUT
              echo "color=#0dcaf0" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Notify Slack
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.status.outputs.emoji }} *${{ github.repository }}* - ${{ inputs.status }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Actor:*\n${{ github.actor }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Notify Discord
        if: ${{ secrets.DISCORD_WEBHOOK_URL != '' }}
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "${{ steps.status.outputs.emoji }} ${{ github.repository }} - ${{ inputs.status }}",
                "color": ${{ steps.status.outputs.color }},
                "fields": [
                  {"name": "Workflow", "value": "${{ github.workflow }}", "inline": true},
                  {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true},
                  {"name": "Actor", "value": "${{ github.actor }}", "inline": true}
                ],
                "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }]
            }'
